// <auto-generated />
using System;
using InspireUs.Congress.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InspireUs.Congress.Infrastructure.Migrations
{
    [DbContext(typeof(CongressDbContext))]
    [Migration("20221129012704_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InspireUs.Congress.Domain.Model.Congress", b =>
                {
                    b.Property<string>("Nth")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Nth");

                    b.ToTable("Congress");

                    b.HasData(
                        new
                        {
                            Nth = "1st"
                        },
                        new
                        {
                            Nth = "2nd"
                        },
                        new
                        {
                            Nth = "3rd"
                        },
                        new
                        {
                            Nth = "4th"
                        },
                        new
                        {
                            Nth = "5th"
                        },
                        new
                        {
                            Nth = "6th"
                        },
                        new
                        {
                            Nth = "7th"
                        },
                        new
                        {
                            Nth = "8th"
                        },
                        new
                        {
                            Nth = "9th"
                        },
                        new
                        {
                            Nth = "10th"
                        },
                        new
                        {
                            Nth = "11th"
                        },
                        new
                        {
                            Nth = "12th"
                        },
                        new
                        {
                            Nth = "13th"
                        },
                        new
                        {
                            Nth = "14th"
                        },
                        new
                        {
                            Nth = "15th"
                        },
                        new
                        {
                            Nth = "16th"
                        },
                        new
                        {
                            Nth = "17th"
                        },
                        new
                        {
                            Nth = "18th"
                        },
                        new
                        {
                            Nth = "19th"
                        },
                        new
                        {
                            Nth = "20th"
                        },
                        new
                        {
                            Nth = "21st"
                        },
                        new
                        {
                            Nth = "22nd"
                        },
                        new
                        {
                            Nth = "23rd"
                        },
                        new
                        {
                            Nth = "24th"
                        },
                        new
                        {
                            Nth = "25th"
                        },
                        new
                        {
                            Nth = "26th"
                        },
                        new
                        {
                            Nth = "27th"
                        },
                        new
                        {
                            Nth = "28th"
                        },
                        new
                        {
                            Nth = "29th"
                        },
                        new
                        {
                            Nth = "30th"
                        },
                        new
                        {
                            Nth = "31st"
                        },
                        new
                        {
                            Nth = "32nd"
                        },
                        new
                        {
                            Nth = "33rd"
                        },
                        new
                        {
                            Nth = "34th"
                        },
                        new
                        {
                            Nth = "35th"
                        },
                        new
                        {
                            Nth = "36th"
                        },
                        new
                        {
                            Nth = "37th"
                        },
                        new
                        {
                            Nth = "38th"
                        },
                        new
                        {
                            Nth = "39th"
                        },
                        new
                        {
                            Nth = "40th"
                        },
                        new
                        {
                            Nth = "41st"
                        },
                        new
                        {
                            Nth = "42nd"
                        },
                        new
                        {
                            Nth = "43rd"
                        },
                        new
                        {
                            Nth = "44th"
                        },
                        new
                        {
                            Nth = "45th"
                        },
                        new
                        {
                            Nth = "46th"
                        },
                        new
                        {
                            Nth = "47th"
                        },
                        new
                        {
                            Nth = "48th"
                        },
                        new
                        {
                            Nth = "49th"
                        },
                        new
                        {
                            Nth = "50th"
                        },
                        new
                        {
                            Nth = "51st"
                        },
                        new
                        {
                            Nth = "52nd"
                        },
                        new
                        {
                            Nth = "53rd"
                        },
                        new
                        {
                            Nth = "54th"
                        },
                        new
                        {
                            Nth = "55th"
                        },
                        new
                        {
                            Nth = "56th"
                        },
                        new
                        {
                            Nth = "57th"
                        },
                        new
                        {
                            Nth = "58th"
                        },
                        new
                        {
                            Nth = "59th"
                        },
                        new
                        {
                            Nth = "60th"
                        },
                        new
                        {
                            Nth = "61st"
                        },
                        new
                        {
                            Nth = "62nd"
                        },
                        new
                        {
                            Nth = "63rd"
                        },
                        new
                        {
                            Nth = "64th"
                        },
                        new
                        {
                            Nth = "65th"
                        },
                        new
                        {
                            Nth = "66th"
                        },
                        new
                        {
                            Nth = "67th"
                        },
                        new
                        {
                            Nth = "68th"
                        },
                        new
                        {
                            Nth = "69th"
                        },
                        new
                        {
                            Nth = "70th"
                        },
                        new
                        {
                            Nth = "71st"
                        },
                        new
                        {
                            Nth = "72nd"
                        },
                        new
                        {
                            Nth = "73rd"
                        },
                        new
                        {
                            Nth = "74th"
                        },
                        new
                        {
                            Nth = "75th"
                        },
                        new
                        {
                            Nth = "76th"
                        },
                        new
                        {
                            Nth = "77th"
                        },
                        new
                        {
                            Nth = "78th"
                        },
                        new
                        {
                            Nth = "79th"
                        },
                        new
                        {
                            Nth = "80th"
                        },
                        new
                        {
                            Nth = "81st"
                        },
                        new
                        {
                            Nth = "82nd"
                        },
                        new
                        {
                            Nth = "83rd"
                        },
                        new
                        {
                            Nth = "84th"
                        },
                        new
                        {
                            Nth = "85th"
                        },
                        new
                        {
                            Nth = "86th"
                        },
                        new
                        {
                            Nth = "87th"
                        },
                        new
                        {
                            Nth = "88th"
                        },
                        new
                        {
                            Nth = "89th"
                        },
                        new
                        {
                            Nth = "90th"
                        },
                        new
                        {
                            Nth = "91st"
                        },
                        new
                        {
                            Nth = "92nd"
                        },
                        new
                        {
                            Nth = "93rd"
                        },
                        new
                        {
                            Nth = "94th"
                        },
                        new
                        {
                            Nth = "95th"
                        },
                        new
                        {
                            Nth = "96th"
                        },
                        new
                        {
                            Nth = "97th"
                        },
                        new
                        {
                            Nth = "98th"
                        },
                        new
                        {
                            Nth = "99th"
                        },
                        new
                        {
                            Nth = "100th"
                        },
                        new
                        {
                            Nth = "101st"
                        },
                        new
                        {
                            Nth = "102nd"
                        },
                        new
                        {
                            Nth = "103rd"
                        },
                        new
                        {
                            Nth = "104th"
                        },
                        new
                        {
                            Nth = "105th"
                        },
                        new
                        {
                            Nth = "106th"
                        },
                        new
                        {
                            Nth = "107th"
                        },
                        new
                        {
                            Nth = "108th"
                        },
                        new
                        {
                            Nth = "109th"
                        },
                        new
                        {
                            Nth = "110th"
                        },
                        new
                        {
                            Nth = "111th"
                        },
                        new
                        {
                            Nth = "112th"
                        },
                        new
                        {
                            Nth = "113th"
                        },
                        new
                        {
                            Nth = "114th"
                        },
                        new
                        {
                            Nth = "115th"
                        },
                        new
                        {
                            Nth = "116th"
                        },
                        new
                        {
                            Nth = "117th"
                        },
                        new
                        {
                            Nth = "118th"
                        });
                });

            modelBuilder.Entity("InspireUs.Congress.Domain.Model.Legislation", b =>
                {
                    b.Property<string>("BillNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CongressNth")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SponserMemberId")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillNumber");

                    b.HasIndex("CongressNth");

                    b.HasIndex("SponserMemberId");

                    b.ToTable("Legislation");
                });

            modelBuilder.Entity("InspireUs.Congress.Domain.Model.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContactUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MemberType")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Party")
                        .HasColumnType("int");

                    b.Property<int?>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("InspireUs.Congress.Domain.Model.Legislation", b =>
                {
                    b.HasOne("InspireUs.Congress.Domain.Model.Congress", "Congress")
                        .WithMany("Legislations")
                        .HasForeignKey("CongressNth")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspireUs.Congress.Domain.Model.Member", "SponserMember")
                        .WithMany("Legislations")
                        .HasForeignKey("SponserMemberId");

                    b.Navigation("Congress");

                    b.Navigation("SponserMember");
                });

            modelBuilder.Entity("InspireUs.Congress.Domain.Model.Member", b =>
                {
                    b.OwnsOne("InspireUs.Congress.Domain.Model.Address", "Address", b1 =>
                        {
                            b1.Property<string>("MemberId")
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Address1")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address1");

                            b1.Property<string>("Address2")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address2");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressCity");

                            b1.Property<int?>("State")
                                .HasColumnType("int")
                                .HasColumnName("AddressState");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AddressZipCode");

                            b1.HasKey("MemberId");

                            b1.ToTable("Member");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("InspireUs.Congress.Domain.Model.District", "District", b1 =>
                        {
                            b1.Property<string>("MemberId")
                                .HasColumnType("nvarchar(10)");

                            b1.Property<int?>("DistrictNumber")
                                .HasColumnType("int")
                                .HasColumnName("DistrictRepresented");

                            b1.Property<int>("State")
                                .HasColumnType("int")
                                .HasColumnName("StateRepresented");

                            b1.HasKey("MemberId");

                            b1.ToTable("Member");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsMany("InspireUs.Congress.Domain.Model.ServiceTime", "ServiceHistory", b1 =>
                        {
                            b1.Property<string>("MemberId")
                                .HasColumnType("nvarchar(10)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("EndYear")
                                .HasColumnType("int");

                            b1.Property<int>("MemberType")
                                .HasColumnType("int");

                            b1.Property<int>("StartYear")
                                .HasColumnType("int");

                            b1.HasKey("MemberId", "Id");

                            b1.ToTable("ServiceTime");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("District")
                        .IsRequired();

                    b.Navigation("ServiceHistory");
                });

            modelBuilder.Entity("InspireUs.Congress.Domain.Model.Congress", b =>
                {
                    b.Navigation("Legislations");
                });

            modelBuilder.Entity("InspireUs.Congress.Domain.Model.Member", b =>
                {
                    b.Navigation("Legislations");
                });
#pragma warning restore 612, 618
        }
    }
}
