version: '3.4'

services:
  inspireus.congress.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - CONGRESS_ADMIN_CONNECTIONSTRING=Server=db;Database=Congress;User Id=sa;Password=Pass@word;TrustServerCertificate=True;
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro