version: '3.4'

services:
  inspireus.congress.api:
    image: ${DOCKER_REGISTRY-}inspireuscongress
    build:
      context: .
      dockerfile: InspireUs.Congress.Api/Dockerfile
    depends_on:
      - selenium-hub
      - db
    restart: always
    networks:
      - hub_network
  inspireus.congress.webscraper:
    image: ${DOCKER_REGISTRY-}inspireuswebscraper
    build:
      context: .
      dockerfile: InspireUs.Congress.WebScraper/Dockerfile
    depends_on:
      - selenium-hub
      - db  
    restart: always
    networks:
      - hub_network
  chrome:
    image: seleniarm/node-chromium:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - hub_network

  firefox:
    image: seleniarm/node-chromium:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - hub_network

  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    restart: always
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - hub_network
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - hub_network
  migration_bundle:
    image: ${DOCKER_REGISTRY-}congress_migrationbdl
    build:
      context: .
      dockerfile: Migrations/Dockerfile
    depends_on:
      - db
    networks:
      - hub_network

networks:
  hub_network:
    driver: bridge